#+title: TemplateNest
#+subtitle: manipulate a generic template structure

~TemplateNest~ is a template engine module for Rust, designed to process nested
templates quickly and efficiently.

Documentation: https://docs.rs/template-nest/

For more details on the idea behind ~Template::Nest~ read:
https://metacpan.org/pod/Template::Nest#DESCRIPTION and
https://pypi.org/project/template-nest/.

The development of this module is sponsored by Tom Gracey (virtual.blue). He
originally authored ~Template::Nest~ in Perl 5.

* News

** v0.3.0 - Upcoming

Migrated away from using custom type ~Filling~ to ~serde_json::Value~. This
change breaks backwards compatibility, the changes required to make previous
code work with this version is minimal. ~serde_json~ has a ~json~ macro that can
be used instead of ~filling~.

+ Added option ~escape_html~: Escape Value::String() by default.

  HTML is expected to live in template files, this provides safety by default
  (in case user forgets to escape user input before using the output).

** v0.2.2 - 2024-01-13

Skipping v0.2.1 due to wrong upload on crates.

+ Added support for several options:
  + ~defaults~
  + ~die_on_bad_params~
  + ~token_escape_char~
+ Added functions to modify a Filling enum (examples included)

** v0.2.0 - 2023-12-06

This release is not backwards compatible, functions ~new~ & ~render~ now return
~Result<String, TemplateNestError>~ instead of ~Result<String, String>~.

+ Custom error enum.
+ Added examples, expanded test suite, improved docs.
+ Added support for several options:
  + ~fixed_indent~
  + ~show_labels~
  + ~comment_delimiters~

** v0.1.0 - 2023-11-26

+ Initial Release.

* Other Implementations

- [[https://metacpan.org/pod/Template::Nest][Template::Nest (Perl 5)]]
- [[https://pypi.org/project/template-nest/][template-nest (Python)]]
- [[https://raku.land/zef:jaffa4/Template::Nest::XS][Template::Nest::XS (Raku)]]
- [[https://raku.land/zef:andinus/Template::Nest::Fast][Template::Nest::Fast (Raku)]]
